//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaglikkDBEntities : DbContext
    {
        public SaglikkDBEntities()
            : base("name=SaglikkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<Giris> Giris { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<Hastalik> Hastalik { get; set; }
        public virtual DbSet<Hastane> Hastane { get; set; }
        public virtual DbSet<Ilac> Ilac { get; set; }
        public virtual DbSet<Poliklinik> Poliklinik { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tahlil> Tahlil { get; set; }
        public virtual DbSet<Tahlil_Tur> Tahlil_Tur { get; set; }
    }
}
