//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaglikApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tahlil
    {
        public int ID { get; set; }
        public int TC { get; set; }
        public int Tahlil_Tur { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Glikoz { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> Ürebilinojen { get; set; }
        public Nullable<int> B12 { get; set; }
        public Nullable<int> Demir { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Tahlil_Tur Tahlil_Tur1 { get; set; }
    }
}
